### ISSUE TITLE
Regex Channel Identifier Retrieval Issue

### ISSUE THREAD

**Issue by Travis-Owens** [KeshBotics/keshbotics3#12]
https://github.com/KeshBotics/keshbotics3/blob/c6fc04c30135392041e0aaf80b3716ccba0f04c4/API/classes/youtube/youtube_channel_id.py#L66

Successful test cases (examples):
Input:
`https://youtube.com/c/xxxx`
`https://youtube.com/channel/xxxx`
`https://youtube.com/user/xxxx`
*Also accepts `www` and `gaming` sub-domains.

Ouput:
`xxxx`

Failed test case:
Input:
`https://www.youtube.com/c/KárolyZsolnai`

Ouput: 
`K`

Expected Output:
`KárolyZsolnai`

**Comment by Alireza-Sampour** [comment]
Hi @Travis-Owens, I will edit the regex pattern and make pull request for this issue, assign this to me. :)
