### ISSUE TITLE
Regex Channel Identifier Retrieval Issue for "/c/" and Integers

### ISSUE THREAD

**Issue by Travis-Owens** [KeshBotics/keshbotics3#16]
https://github.com/KeshBotics/keshbotics3/blob/64e1ed3e9456638b1e88056c25f001c0f8dbca0a/API/classes/youtube/youtube_channel_id.py#L65

This regex should also support the "/c/" variant of the YouTube channel URL.

Input:
`https://youtube.com/c/xxxx`

Output:
`c`

Expected Output:
`xxxx`

This regex should support channel identifiers that start/end/contain integers.

Input:
`https://youtube.com/user/xxxx1`

Output:
`xxxx`

Expected Output:
`xxxx1`

**Comment by Alireza-Sampour** [comment]
@Travis-Owens assign this to me, I will do it.
